# Generated by Django 2.0.1 on 2018-01-03 22:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique ID for stock purchase', primary_key=True, serialize=False)),
                ('purchased', models.DateTimeField(null=True)),
                ('price_at_purchase', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of stock', max_length=250)),
                ('symbol', models.CharField(help_text='Enter the stocks name', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ownedstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Stock'),
        ),
    ]
