# Generated by Django 2.0.1 on 2018-01-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20180104_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(help_text='Enter the stocks name', max_length=20),
        ),
    ]
