# Generated by Django 2.0.1 on 2018-01-04 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20180104_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedstock',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ownedstock',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Trader'),
        ),
    ]
