# Generated by Django 2.0.1 on 2018-01-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20180104_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedstock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
