# Generated by Django 2.0.1 on 2018-01-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20180104_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownedstock',
            old_name='purchased',
            new_name='time_of_purchase',
        ),
    ]
